### ISSUE TITLE
Match Sublime and TextMate version?

### ISSUE THREAD

**Issue by simurai** [atom/solarized-dark-syntax#55]
After looking into #47 + #51, it seems that this theme uses the Solarized colors but the syntax highlighting in `base.less` is different to other Solarized ports like for Sublime or TextMate.

For example a generic `.variable` in Atom's version uses `@cyan`, but it's `@blue` in Sublime/TextMate. Might be a good idea to match it in Atom too. Then we shouldn't need to override it for every language separately because people make issues like the above.

So instead of 

```less
.variable { color: @cyan; } // base.less

.source.coffee .variable { color: @blue; } // coffee.less
.source.java .variable { color: @blue; } // java.less
.source.javascript .variable { color: @blue; } // javascript.less
.source.go .variable { color: @blue; } // go.less
// etc.
```

change to

```less
.variable { color: @blue; } // base.less
```

It would be a (big) change for people that got used to the Atom version and that use a language that doesn't get overridden. But I think matching the base styles to what Sublime/TextMate are using would benefit all the users that switch over to Atom or are used to these versions. And less overriding should be needed.

@schmittyjd How do you feel about it?
